// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth/local/models/auth_box.dart';
import 'features/vehicle/local/models/vehicle_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 246773346461569067),
    name: 'AuthBox',
    lastPropertyId: const obx_int.IdUid(2, 8018146305578317912),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1793962085801517151),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8018146305578317912),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 35448434071534752),
    name: 'VehicleBox',
    lastPropertyId: const obx_int.IdUid(2, 5418453194926022068),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3111429568431721065),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5418453194926022068),
        name: 'remoteId',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 35448434071534752),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthBox: obx_int.EntityDefinition<AuthBox>(
      model: _entities[0],
      toOneRelations: (AuthBox object) => [],
      toManyRelations: (AuthBox object) => {},
      getId: (AuthBox object) => object.id,
      setId: (AuthBox object, int id) {
        object.id = id;
      },
      objectToFB: (AuthBox object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = AuthBox(id: idParam, remoteId: remoteIdParam);

        return object;
      },
    ),
    VehicleBox: obx_int.EntityDefinition<VehicleBox>(
      model: _entities[1],
      toOneRelations: (VehicleBox object) => [],
      toManyRelations: (VehicleBox object) => {},
      getId: (VehicleBox object) => object.id,
      setId: (VehicleBox object, int id) {
        object.id = id;
      },
      objectToFB: (VehicleBox object, fb.Builder fbb) {
        final remoteIdOffset = fbb.writeString(object.remoteId);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, remoteIdOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final remoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = VehicleBox(id: idParam, remoteId: remoteIdParam);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthBox] entity fields to define ObjectBox queries.
class AuthBox_ {
  /// See [AuthBox.id].
  static final id = obx.QueryIntegerProperty<AuthBox>(
    _entities[0].properties[0],
  );

  /// See [AuthBox.remoteId].
  static final remoteId = obx.QueryStringProperty<AuthBox>(
    _entities[0].properties[1],
  );
}

/// [VehicleBox] entity fields to define ObjectBox queries.
class VehicleBox_ {
  /// See [VehicleBox.id].
  static final id = obx.QueryIntegerProperty<VehicleBox>(
    _entities[1].properties[0],
  );

  /// See [VehicleBox.remoteId].
  static final remoteId = obx.QueryStringProperty<VehicleBox>(
    _entities[1].properties[1],
  );
}
